#!/bin/sh -e

cargo build --release
install -Dm755 target/release/alacritty "$1/usr/bin/alacritty"
install -Dm644 extra/logo/alacritty-term.svg "$1/usr/share/pixmaps/Alacritty.svg"
install -Dm644 extra/linux/Alacritty.desktop "$1/usr/share/applications/Alacritty.desktop"
install -Dm644 alacritty.yml "$1/etc/alacritty/alacritty.yml"

