#!/bin/sh -e

# Modify termcap and terminfo
sed -i '/v0/{n;s/new:/new:kb=^?:/}' termcap
printf '\tkbs=\\177,\n' >> terminfo

# Configure with specified options
TERMINFO=/usr/share/terminfo ./configure $XORG_CONFIG --with-app-defaults=/etc/X11/app-defaults

# Build
make

# Install
make install

# Create desktop entry directory
mkdir -pv /usr/share/applications

# Copy desktop files
cp -v *.desktop /usr/share/applications/

