#!/bin/sh
export LIBRARY_PATH=$XORG_PREFIX/lib

autoreconf -fi
./configure --prefix=/usr \
            --sysconfdir=/etc \
            --disable-static \
            --docdir=/usr/share/doc/openbox-3.6.1

make
make install
rm -v /usr/share/xsessions/openbox-{gnome,kde}.desktop

